In [5]:
c=10
print(c)

10


In [6]:
import numpy as np

a=np.array([2,3,41,3])
a

array([ 2,  3, 41,  3])

In [24]:
print(a[2])

type(a)
a[1]


41


3

In [34]:
b=np.array([[2,3,4],
          [12,3,1],
            [12,3,1],
          [2,1,1]])

b.shape
print(b.T)

[[ 2 12 12  2]
 [ 3  3  3  1]
 [ 4  1  1  1]]


In [37]:
i=np.argmin(b.T)
i

7

In [47]:
# element with max frequency

a=np.array([1,2,2,33,1,21,21,31,2,2,3,41,21,21,212,212,2,21,12,22,3,2,32,33,32,332])

b=np.unique(a,return_counts=True)

index=np.argmax(b[1])
print("The maximum frequency element is ", index)

index=np.argmin(b[1])
print("The minimum frequency element is ", index)






The maximum frequency element is  1
The minimum frequency element is  3


In [ ]:
# slicing matrx

matrix=np.array([[2,3,4],
          [12,3,1],
            [12,3,1],
          [2,1,1]])


submat=matrix[0:2,1:4]
print(submat,submat.shape)



[[3 4]
 [3 1]] (2, 2)


In [ ]:
shubham="fine"

print(shubham)